#:schema node_modules/wrangler/config-schema.json
name = "lisible"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[vars]
# Ne mets pas tes secrets ici, mais v√©rifie qu'ils sont bien dans le Dashboard
NEXT_PUBLIC_BASE_URL = "https://lisible.biz"
