name = "lisible"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"
path = ".vercel/output"

[vars]
# Tes variables secrètes restent gérées dans le dashboard Cloudflare
