name = "lisible"
pages_build_output_dir = ".vercel/output/static" # Doit correspondre Ã  la config Cloudflare
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# Tes variables ici
