#:schema node_modules/wrangler/config-schema.json
name = "lisible"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

# LE RÃ‰GLAGE CRUCIAL :
pages_build_output_dir = ".vercel/output"
