#:schema node_modules/wrangler/config-schema.json
name = "lisible"
pages_build_output_dir = ".vercel/output"

[vars]
# Tes variables sont déjà dans le dashboard, pas besoin de les mettre ici.

[compatibility_flags]
nodejs_compat = true
