#:schema node_modules/wrangler/config-schema.json
name = "lisible"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# AJOUTE /static ICI :
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_BASE_URL = "https://lisible.biz"
