name = "lisible"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# Ne pas forcer l'edge runtime ici, laisser Next.js gÃ©rer
# Ajoute tes autres variables ici si besoin
