name: Update Monthly Badge
on:
  schedule:
    - cron: '0 0 1 * *' # S'ex√©cute le 1er de chaque mois √† minuit
  workflow_dispatch: # Permet le lancement manuel depuis l'onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Mise √† jour vers v4 (plus rapide et s√©curis√©e)

      - name: Use Node.js
        uses: actions/setup-node@v4 # Mise √† jour vers v4
        with:
          node-version: '20' # Utilisation de la version LTS actuelle

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          fi

      - name: Calculate Winner
        run: node scripts/calculate-winner.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "Lisible Bot"
          git config --global user.email "bot@lisible.com"
          git add data/awards/winner.json data/awards/reader.json
          # Le commit ne se fera que s'il y a des changements pour √©viter l'√©chec du workflow
          git diff --quiet && git diff --staged --quiet || (git commit -m "üèÜ Mise √† jour des troph√©es mensuels" && git push)
